(function () {
  "use strict";

  window.TSUBASA_CONFIG = Object.freeze({
    supabaseUrl: "https://spyopczqtxypqjbhylzf.supabase.co",
    publishableKey: "sb_publishable_0OHZyJkYkTjqJoIUGUAKNw_R1ZvEzUg",
    schema: "rev2",
    publicUrl: "https://infoworks-jp.github.io/tsubasa-business-system-codex/"
  });

  const nativeFetch=window.fetch.bind(window);
  window.fetch=async function(input,init){
    const url=typeof input==='string'?input:(input&&input.url)||'';
    if(!url.includes('/rest/v1/historical_daily_performance'))return nativeFetch(input,init);
    const baseInit=Object.assign({},init||{}),baseHeaders=Object.assign({},baseInit.headers||{});
    const fetchPage=async(from,to)=>{const pageInit=Object.assign({},baseInit,{headers:Object.assign({},baseHeaders,{Range:from+'-'+to})});const res=await nativeFetch(input,pageInit);if(!res.ok)throw new Error(await res.text());return res.json()};
    const all=[];for(let from=0;;from+=1000){const page=await fetchPage(from,from+999);all.push(...page);if(page.length<1000)break}
    return new Response(JSON.stringify(all),{status:200,headers:{'Content-Type':'application/json','X-Tsubasa-Rows':String(all.length)}});
  };

  const yen=v=>'¥'+Math.round(Number(v||0)).toLocaleString();
  function iframePage(src,title,note){const host=document.getElementById('host');host.innerHTML=`<div class="panel"><h2 style="margin-top:0">${title}</h2><div class="notice ok" style="margin-bottom:10px">${note}</div><iframe src="${src}" style="width:100%;height:1250px;border:1px solid #d9e2f3;border-radius:10px;background:#fff" loading="lazy"></iframe></div>`}
  async function fetchHistorical(){const c=window.TSUBASA_CONFIG,u=c.supabaseUrl+'/rest/v1/historical_daily_performance?select=business_date,sales,source_month&order=business_date.asc';const r=await window.fetch(u,{headers:{apikey:c.publishableKey,'Accept-Profile':'rev2'}});if(!r.ok)throw new Error(await r.text());return r.json()}
  async function fetchHistoricalMonthly(){const c=window.TSUBASA_CONFIG,u=c.supabaseUrl+'/rest/v1/historical_monthly_performance?select=month_start,sales_total,customer_count,average_spend,source_page,verification_status&order=month_start.asc';const r=await nativeFetch(u,{headers:{apikey:c.publishableKey,'Accept-Profile':'rev2'},cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
  function histMonthly(rows){const hm={};rows.forEach(x=>{const k=String(x.month_start).slice(0,7);hm[k]={sales:Number(x.sales_total),customers:Number(x.customer_count),avg:Number(x.average_spend),source_page:Number(x.source_page),series:'長期原票系列'}});return hm}

  async function renderExecutive(){
    const host=document.getElementById('host');host.innerHTML='<div class="panel">みんな向け画面を読み込み中...</div>';
    try{
      const api=window.rev2Api,[boot,histRows,ticketRows]=await Promise.all([api('/api/bootstrap'),api('/api/historical-monthly'),api('/api/monthly')]),active=boot.active_month;
      const [ov,q,hourly,products,daily]=await Promise.all([api('/api/overview/'+active),api('/api/quality/'+active),api('/api/hourly/'+active),api('/api/products/'+active),api('/api/daily/'+active)]);
      const hm=histMonthly(histRows.map(x=>({month_start:x.month,sales_total:x.sales,customer_count:x.customers,average_spend:x.avg_spend,source_page:x.source_page}))),ticket=Object.fromEntries(ticketRows.map(x=>[x.month,x])),m=active.slice(5),years=['2023','2024','2025','2026'],same=years.map(y=>({year:y,...(hm[y+'-'+m]||{})}));
      const recentSummer=['06','07','08'].map(mm=>({month:mm,original:hm['2026-'+mm],ticket:ticket['2026-'+mm],prior:hm['2025-'+mm]}));
      const hr=(hourly&&hourly.rows)||[],byHour={};hr.forEach(x=>{const h=Number.parseInt(String(x.hour??x.hour_start),10);if(!Number.isFinite(h))return;const z=byHour[h]||(byHour[h]={s:0});z.s+=Number(x.sales??x.sales_amount??x.gross_sales??0)});const topHours=Object.entries(byHour).sort((a,b)=>b[1].s-a[1].s).slice(0,3).map(x=>x[0]+'時').join('・')||'未集計';
      const pcount=Array.isArray(products)?products.length:0,dailyCount=(daily||[]).filter(x=>Number(x.total_sales||0)>0).length,coverage=q.coverage||{};
      const dataIssues=['長期原票には月別の客数が記載されています。客単価も「売上÷客数」で算出できます。月次比較へ反映しました。'];
      if(coverage.product_status!=='complete')dataIssues.push(active+'の商品別明細は '+(coverage.product_status==='unregistered'?'未登録':`${coverage.product_days}/${coverage.operating_days}営業日分`)+'です。日計売上は '+yen(q.daily)+'、うち商品内訳未取得は '+yen(q.product_breakdown_pending_total)+' です。商品グラフやビールを0円とは扱いません。');
      if(coverage.hourly_status!=='complete')dataIssues.push('時間帯別は '+(coverage.hourly_days||0)+'日分、日計は '+(coverage.operating_days||dailyCount)+'営業日分。時間帯は発行ベースの一部データです。');
      if(q.source_scope?.retained_original)dataIssues.push('原本恒久保存は '+q.source_scope.retained_original+'。保存先ID・SHA-256・容量がそろった写真だけを「原本あり」と判定します。'+(q.missing_retained_source_dates?.length?'未保存日：'+q.missing_retained_source_dates.join('、')+'。':'対象日の原本を追跡可能です。'));
      if(!q.matched)dataIssues.push('「要確認」の主因は、商品別・時間帯別など内訳データの不足です。日計売上が欠損・ゼロという意味ではありません。');
      dataIssues.push('シフトは端末内保存（localStorage）のため、別端末とはまだ自動共有されません。');
      const sameHtml=same.map(x=>`<tr><td>${x.year}年${Number(m)}月</td><td>${x.sales==null?'データなし':yen(x.sales)}</td><td>${x.customers==null?'—':Number(x.customers).toLocaleString()+'人'}</td><td>${x.avg==null?'—':yen(x.avg)}</td></tr>`).join('');
      const summerHtml=recentSummer.map(x=>`<tr><td>${Number(x.month)}月</td><td>${x.original?yen(x.original.sales):'データなし'}</td><td>${x.original?x.original.customers.toLocaleString()+'人':'データなし'}</td><td>${x.original?yen(x.original.avg):'データなし'}</td><td>${x.ticket?yen(x.ticket.sales):'データなし'}</td><td>${x.ticket?x.ticket.customers.toLocaleString()+'人':'データなし'}</td><td>${x.ticket?yen(x.ticket.avg_spend):'データなし'}</td><td>${x.prior&&x.original?((x.original.sales/x.prior.sales-1)*100).toFixed(1)+'%':'—'}</td></tr>`).join('');
      host.innerHTML=`<div class="panel" style="border-left:7px solid #17365d"><h2 style="margin:0 0 8px">みんなが最初に見る画面</h2><div class="sub">結論 → 数字 → 原因 → 今やること、の順だけで読めます。</div></div>
      <div class="cards" style="margin-top:10px"><div class="card"><div class="label">${active.replace('-','年')}月 売上</div><div class="big">${yen(ov.month_sales)}</div><div class="sub">登録済み日計</div></div><div class="card"><div class="label">平均日商</div><div class="big">${yen(ov.avg_daily)}</div><div class="sub">売上÷営業日数</div></div><div class="card"><div class="label">客単価</div><div class="big">${yen(ov.avg_spend)}</div><div class="sub">売上÷客数</div></div><div class="card"><div class="label">データ状態</div><div class="big">${q.status}</div><div class="sub">${q.matched?'照合済み':'内訳に未登録あり'}</div></div></div>
      <div class="grid2" style="margin-top:12px"><div class="panel"><h2>① まず結論</h2><div class="insight"><b>9月は強い。</b><br>27万円台の日が複数あり、需要は残っています。課題はピークの再現と弱い時間帯の人件費効率です。</div><div class="insight"><b>長期では売上だけでなく客数と客単価も見ます。</b><br>原票の月次累計客数を反映し、客単価を計算できるようにしました。</div><div class="insight"><b>強い時間帯候補：</b> ${topHours}</div></div><div class="panel"><h2>② 今、何が未登録か</h2>${dataIssues.map(x=>`<div class="notice" style="margin:7px 0">${x}</div>`).join('')}</div></div>
      <div class="grid2" style="margin-top:12px"><div class="panel"><h2>③ 同月4年比較・長期原票系列</h2><table><thead><tr><th>年</th><th>売上</th><th>客数</th><th>客単価</th></tr></thead><tbody>${sameHtml}</tbody></table></div><div class="panel"><h2>④ 2026年 夏3か月・2系列比較</h2><div class="notice"><b>長期原票系列と券売機確定系列は別物です。</b> 黙って置き換えません。</div><div class="scroll"><table><thead><tr><th>月</th><th>原票売上</th><th>原票客数</th><th>原票客単価</th><th>券売機売上</th><th>券売機客数</th><th>券売機客単価</th><th>原票前年比</th></tr></thead><tbody>${summerHtml}</tbody></table></div></div></div>
      <div class="panel" style="margin-top:12px"><h2>⑤ みんなでこの順にやる</h2><div class="insight"><b>1.</b> 20〜23時へ人員集中。深夜2時台は採算を毎月検証。</div><div class="insight"><b>2.</b> 9月の商品別データを確認して、売れている商品・ビール・低回転品を確定する。</div><div class="insight"><b>3.</b> 売上・客数・客単価を前年同月とセットで見る。</div><div class="insight"><b>4.</b> 値上げは基本ラーメンとトッピングの整合を崩さない。</div></div>`;
    }catch(e){host.innerHTML='<div class="panel notice ng">みんなのトップの読込に失敗しました。<br>'+String(e.message||e)+'</div>'}
  }

  function showNoProductData(tab){const title=tab==='beer'?'ビール・セット':tab==='abc'?'ABC分析':'商品別・全商品',q=state?.quality||{},c=q.coverage||{},partial=c.product_status==='partial',rows=Array.isArray(state?.products)?state.products:[];if(!partial){document.getElementById('host').innerHTML=`<div class="panel"><h2>${title}</h2><div class="notice ng"><b>未登録・分析不可</b><br>日計売上 ${yen(q.daily)} は確認済みです。商品名別の内訳が未登録であり、売上0円という意味ではありません。商品別原票が登録されるまで通常グラフは出しません。</div></div>`;return}const sorted=[...rows].sort((a,b)=>Number(b.sales)-Number(a.sales)),beer=sorted.filter(x=>/ビール/.test(x.name)),shown=tab==='beer'?beer:sorted;const detail=shown.length?table(['商品','登録済み出数','登録済み売上'],shown.map(x=>[x.name,Number(x.qty).toLocaleString(),yen(x.sales)]),true):'<div class="notice ng">登録済み明細を取得できません。</div>';document.getElementById('host').innerHTML=`<div class="panel"><h2>${title}</h2><div class="cards"><div class="card"><div class="label">月の日計売上</div><div class="big">${yen(q.daily)}</div><div class="sub">全営業日の確定売上</div></div><div class="card"><div class="label">商品内訳登録済み</div><div class="big">${yen(q.registered_product_total)}</div><div class="sub">${c.product_days}日分</div></div><div class="card"><div class="label">商品内訳未取得売上</div><div class="big">${yen(q.product_breakdown_pending_total)}</div><div class="sub">売上0円ではありません</div></div></div><div class="notice ng" style="margin-top:12px"><b>${c.operating_days}営業日中${c.product_days}日分の原票を登録済み</b><br>下表は登録済み日だけの参考集計です。月全体の順位・構成比・ABC判定は、全営業日分がそろうまで確定しません。</div><div style="margin-top:12px">${detail}</div></div>`}
  window.showNoProductData=showNoProductData;

  function injectHistoryCustomerPanel(){if(!location.pathname.endsWith('/history.html'))return;setTimeout(async()=>{try{const hist=await fetchHistoricalMonthly(),hm=histMonthly(hist),main=document.querySelector('main');if(!main||document.getElementById('histCustomerPanel'))return;const values=Object.keys(hm).map(month=>({month,...hm[month]}));const p=document.createElement('div');p.id='histCustomerPanel';p.className='panel';p.style='margin:11px 0';p.innerHTML=`<h2>月別 売上・客数・客単価（長期原票系列）</h2><div class="sub">37ページ原票（うち33ページは人件費表）の月末累計客数をDB登録。客単価＝月売上÷月客数。券売機確定系列とは混ぜません。</div><div class="toolbar"><label>並び順 <select id="histMonthlySort"><option value="month">年月順</option><option value="sales">売上順</option><option value="customers">客数順</option><option value="avg">客単価順</option></select></label></div><div class="scroll"><table><thead><tr><th>月</th><th>売上</th><th>客数</th><th>客単価</th><th>原票</th></tr></thead><tbody id="histMonthlyBody"></tbody></table></div>`;const draw=()=>{const key=p.querySelector('#histMonthlySort').value,rows=[...values].sort(key==='month'?(a,b)=>a.month.localeCompare(b.month):(a,b)=>b[key]-a[key]);p.querySelector('#histMonthlyBody').innerHTML=rows.map(x=>`<tr><td>${x.month}</td><td>${yen(x.sales)}</td><td>${x.customers.toLocaleString()}人</td><td>${yen(x.avg)}</td><td>${x.source_page}頁</td></tr>`).join('')};p.querySelector('#histMonthlySort').addEventListener('change',draw);draw();const toolbar=main.querySelector('.toolbar');toolbar?toolbar.after(p):main.prepend(p)}catch(e){console.error(e)}},900)}

  function integrate(){
    injectHistoryCustomerPanel();
    const tabs=document.querySelector('.tabs'),nav=document.querySelector('header nav');
    if(nav)nav.innerHTML='<button onclick="showTab(\'executive\')">みんなのトップ</button><button onclick="showTab(\'overview\')">通常ダッシュボード</button><button onclick="showTab(\'historyAll\')">長期実績</button><button onclick="showTab(\'consultAll\')">長期コンサル</button><button onclick="showTab(\'shiftAll\')">シフト</button>';
    if(tabs){const lead=document.createElement('div');lead.style='display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:0 0 12px';lead.innerHTML='<button id="t_executive" style="background:#17365d;color:#fff" onclick="showTab(\'executive\')">みんなのトップ</button><button id="t_historyAll" onclick="showTab(\'historyAll\')">長期比較</button><button id="t_consultAll" onclick="showTab(\'consultAll\')">コンサル判断</button><button id="t_shiftAll" onclick="showTab(\'shiftAll\')">シフト作成</button>';tabs.parentNode.insertBefore(lead,tabs);const note=document.createElement('div');note.className='notice ok';note.style='margin-bottom:10px';note.innerHTML='<b>見方：</b> 最初は「みんなのトップ」を見てください。必要な時だけ長期比較・商品・時間帯・シフトへ進みます。';tabs.parentNode.insertBefore(note,tabs)}
    if(typeof window.showTab==='function'){const original=window.showTab;window.showTab=async function(tab){document.querySelectorAll('[id^="t_"]').forEach(x=>x.classList.remove('active'));const b=document.getElementById('t_'+tab);if(b)b.classList.add('active');if(tab==='executive')return renderExecutive();if(tab==='historyAll')return iframePage('./history.html','長期実績・4年比較','売上だけでなく、原票の客数と計算客単価も表示します。');if(tab==='consultAll')return iframePage('./consulting-history.html','長期コンサル分析','社会情勢・インバウンド・経営批評・やるべきことを確認します。');if(tab==='shiftAll')return iframePage('./shift/','シフト作成','売上ピークと深夜割増を見ながら作成します。');if(['products','abc','beer'].includes(tab)&&state?.quality?.coverage?.product_status!=='complete')return showNoProductData(tab);return original(tab)};setTimeout(()=>window.showTab('executive'),1200)}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',integrate);else integrate();
})();
