begin;
alter table public.ticket_ocr_imports add column if not exists queue_status text not null default 'new' check (queue_status in ('new', 'confirmed', 'saved', 'error')), add column if not exists business_date date not null default current_date, add column if not exists confirmed_at timestamptz, add column if not exists saved_at timestamptz, add column if not exists error_message text;
create table if not exists public.ticket_product_sales_totals (id uuid primary key default gen_random_uuid(), business_date date not null, product_id uuid not null references public.products(id), quantity integer not null default 0, amount integer not null default 0, source_import_id uuid references public.ticket_ocr_imports(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint ticket_product_sales_totals_quantity_check check (quantity >= 0), constraint ticket_product_sales_totals_amount_check check (amount >= 0), constraint ticket_product_sales_totals_unique unique (business_date, product_id));
create index if not exists ticket_product_sales_totals_business_date_idx on public.ticket_product_sales_totals(business_date desc);
alter table public.ticket_product_sales_totals enable row level security;
do $$ begin if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ticket_product_sales_totals' and policyname = 'ticket_product_sales_totals_select_admin') then create policy ticket_product_sales_totals_select_admin on public.ticket_product_sales_totals for select using (auth.role() = 'authenticated'); end if; end $$;
do $$ begin if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ticket_product_sales_totals' and policyname = 'ticket_product_sales_totals_insert_admin') then create policy ticket_product_sales_totals_insert_admin on public.ticket_product_sales_totals for insert with check (auth.role() = 'authenticated'); end if; end $$;
do $$ begin if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ticket_product_sales_totals' and policyname = 'ticket_product_sales_totals_update_admin') then create policy ticket_product_sales_totals_update_admin on public.ticket_product_sales_totals for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated'); end if; end $$;
commit;
